# Generated by Django 5.1.1 on 2025-08-21 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_pub_date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_pub_date',
            new_name='pub_date',
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг жанра'),
        ),
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.category', verbose_name='Категория'),
        ),
    ]
